### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by manumanuk**
New changes:
* Implemented React connection to Electron, fixed issues with previous implementation
* Completed basic Navbar UI to specification + animated transition between pages
* Created the three main pages with fade-in effects
* Implemented react browser router to make sure pointer is always synced up with page

Remaining changes:
* Need to make cursor position more responsive by getting exact x-y position of the three links in the navbar
* The two indicators at the bottom have hardcoded states currently (need to get data from API and sync)
* Implementing the actual pages

### CODE REVIEW

**Comment by manumanuk** [comment]
[#21: UI Home page](https://trello.com/c/rbJCsRoE/21-21-ui-home-page)

**Comment by manumanuk** [comment]
[#28: UI Navbar + Infrastructure](https://trello.com/c/qqHkDI93/28-28-ui-navbar-infrastructure)

**Comment by manumanuk** [comment]
[#18: Animate the transitions of the UI screens.](https://trello.com/c/NCOgfwrK/18-18-animate-the-transitions-of-the-ui-screens)

**Comment by Awbmilne** [comment]
Great work!

Preview for those interested:
UI Demo

**Comment by Awbmilne** [comment]
_Note: @manumanuk _
You have a "Remaining Changes" section in your main comment. If you have changes that you are still planning to make before this PR is merged, You should mark the Pull Request as a "Draft" so that everyone knows its not done yet. There is a little button in the Reviewers section on the right bar.

**Review by Awbmilne — APPROVED** [review]
Looks Good!

_Note: @manumanuk_
You have a "Remaining Changes" section in your main comment. If you have changes that you are still planning to make before this PR is merged, You should mark the Pull Request as a "Draft" so that everyone knows its not done yet. There is a little button in the Reviewers section on the right bar.

**Comment by manumanuk** [comment]
> Looks Good!
> 
> _Note: @manumanuk_
> You have a "Remaining Changes" section in your main comment. If you have changes that you are still planning to make before this PR is merged, You should mark the Pull Request as a "Draft" so that everyone knows its not done yet. There is a little button in the Reviewers section on the right bar.

Thanks for the review; those were just some non-critical changes to be considered in future updates, I'll name it more appropriately for the next PR

**Pull request merged**
